### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by tenhobi** [brianamarie/Portfolio#2]
_Just a good tip, excuse me._

If you rename your repository to `nickname.github.io` and then you create `CNAME` file with your domain, `https://brianamarie.github.io` will be redirected to that site.

Or if you will not create `CNAME` file, page will be created from your repo, but I do not know how that works with that crazy HTML preprocessor.

Also if you wanna allow access some project, you can use `nickname.github.io/repository` and if that repository has gh-pages brant, it will use it for render GitHub page. :-)

On my repository I use simple redirect, so take a look, if you want. https://github.com/HoBi/hobi.github.io But it is not pretty. :(

**Comment by tenhobi** [comment]
ping @brianamarie

**Comment by brianamarie** [comment]
I did try to do this, but it messed up some things with my DNS server and broke my website on the domain name. I want to implement this, but right now I'm linking my site to could-be employers and I can't risk it being down when I'm sending out applications. This is on my to-do list for the not too distant future. Thank you @HoBi :)
